name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.1'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Copy files to EC2
      run: |
        scp -r -o StrictHostKeyChecking=no ./dist ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/app

    - name: SSH into EC2 and update Nginx configuration
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Copy the build files to the Nginx web root
          sudo cp -r /home/ubuntu/app/* /var/www/html/
          
          # Restart Nginx to apply changes
          sudo systemctl restart nginx
        EOF
